server:
  port: ${WEB_PORT:8888}

neutrino:
  proxy:
    protocol:
      max-frame-length: ${MAX_FRAME_LENGTH:2097152}
      length-field-offset: 0
      length-field-length: 4
      initial-bytes-to-strip: 0
      length-adjustment: 0
      read-idle-time: 40
      write-idle-time: 5
      all-idle-time-seconds: 0
    tunnel:
      boss-thread-count: 2
      work-thread-count: 10
      port: ${OPEN_PORT:9000}
      ssl-port: ${SSL_PORT:9002}
      key-store-password: ${STORE_PASS:123456}
      key-manager-password: ${MGR_PASS:123456}
      jks-path: ${JKS_PATH:classpath:/test.jks}
    server:
      boss-thread-count: 5
      work-thread-count: 20
      http-proxy-port: ${HTTP_PROXY_PORT:80}
      https-proxy-port: ${HTTPS_PROXY_PORT:443}
      # 如果不配置，则不支持域名映射
      domain-name: ${DOMAIN_NAME:}
  data:
    db:
      type: ${DB_TYPE:sqlite}
      url: ${DB_URL:jdbc:sqlite:data.db}
      username: ${DB_USER:}
      password: ${DB_PASSWORD:}

#添加MIME印射（如果有需要？）
#是否启用静态文件服务。（可不配，默认为启用）
solon.staticfiles.enable: true
#静态文件的304缓存时长。（可不配，默认为10分钟）
solon.staticfiles.maxAge: 600
#添加静态目录映射。（按需选择）#v1.11.0 后支持
solon.staticfiles.mappings:
  - path: "/"
    repository: "./neutrino-proxy-admin/dist/" #2.添加资源路径（仓库只能是目录）

mybatis.db:
  typeAliases:    #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    - "org.dromara.neutrinoproxy.server.dal.entity"
  mappers:        #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）//支持 ** 或 * 占位符
    - "classpath:mapper/*.xml"
    - "org.dromara.neutrinoproxy.server.dal"
  configuration:   #扩展配置（要与 MybatisConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapUnderscoreToCamelCase: true
  globalConfig:    #全局配置（要与 GlobalConfig 类的属性一一对应）
    banner: true
