neutrino:
  application:
    name: neutrino-proxy-server
  http:
    enable: true
    port: 8888
    context-path: /
    max-content-length-desc: 128K
    static-resource:
      locations:
        - "neutrino-proxy-admin/dist/"

  proxy:
    protocol:
      max-frame-length: 2097152
      length-field-offset: 0
      length-field-length: 4
      initial-bytes-to-strip: 0
      length-adjustment: 0
      read-idle-time: 40
      write-idle-time: 10
      all-idle-time-seconds: 0
    server:
      port: 9000
      ssl-port: 9002
      key-store-password: 123456
      key-manager-password: 123456
      jks-path: classpath:/test.jks
  data:
    db:
#      type: sqlite
#      url: jdbc:sqlite:data.db
#      driver-class: org.sqlite.JDBC
      type: mysql
      url: jdbc:mysql://localhost:3306/neutrino-proxy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
      driver-class: com.mysql.jdbc.Driver
      username: "******"
      password: "******"
