neutrino:
  application:
    name: neutrino-proxy-client

  proxy:
    protocol:
      max-frame-length: 2097152
      length-field-offset: 0
      length-field-length: 4
      initial-bytes-to-strip: 0
      length-adjustment: 0
      read-idle-time: 40
      write-idle-time: 8
      all-idle-time-seconds: 0
    client:
      thread-count: 50
      key-store-password: 123456
      jks-path: classpath:/test.jks
      server-ip: localhost
      server-port: 9002
      ssl-enable: true
      obtain-license-interval: 5
      license-key: b0a907332b474b25897c4dcb31fc7eb6
