name: jar release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        # 'ubuntu-latest', 'windows-latest', 'macos-latest'
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: setup node v13.12.0
      uses: actions/setup-node@v3
      with:
        node-version: 13.12.0
        cache: 'npm'
        cache-dependency-path: neutrino-proxy-admin/package-lock.json
    - name: build neutrino-proxy-admin
      run: |
        cd neutrino-proxy-admin
        npm install
        npm run build:dev
        cp -rf ./dist/ ./../neutrino-proxy-server/src/main/resources/static/
    - name: GitHub Action for GraalVM JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.7' # for a specific JDK 17; or '17' for the latest JDK 17
        distribution: 'graalvm' # New 'distribution' option
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven (neutrino-proxy-server)
      run: |
        mvn clean install -pl neutrino-proxy-core -am -DskipTests --no-transfer-progress
        cd neutrino-proxy-server
        mvn clean native:compile -P native --file pom.xml --no-transfer-progress
    - name: Archive zip (neutrino-proxy-server)
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'neutrino-proxy-server/target/neutrino-proxy-server'
        filename: neutrino-proxy-server-${{ matrix.os }}.zip
    - name: Build with Maven (neutrino-proxy-client)
      run: |
        cd neutrino-proxy-client
        mvn clean package --file pom.xml --no-transfer-progress
        mvn clean native:compile -P native --file pom.xml --no-transfer-progress
    - name: Archive zip (neutrino-proxy-client)
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'neutrino-proxy-client/target/neutrino-proxy-client'
        filename: neutrino-proxy-client-${{ matrix.os }}.zip
    # GitHub 上创建 release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          neutrino-proxy-server/target/neutrino-proxy-server.jar
          neutrino-proxy-client/target/neutrino-proxy-client.jar
          neutrino-proxy-server-${{ matrix.os }}.zip
          neutrino-proxy-client-${{ matrix.os }}.zip
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}